version: '3.9'
services:
  backend:
    build: ./apps/backend
    env_file: .env
    ports:
      - "8000:8000"
  frontend:
    build: ./apps/frontend
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE: http://backend:8000
    depends_on:
      - backend
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
